## Análisis de riesgo financiero

### Librerías

In [1]:
import pandas as pd
import duckdb
import os
import matplotlib.pyplot as plt

Se genera la lista de archivos

In [3]:
data_folder = 'data'

tables = os.listdir(data_folder)

files = {}
for t in tables:
    if t[-3:] == 'csv':
        files[t[:-4]] = t

In [5]:
con = duckdb.connect() # o duckdb.connect('mi_base.duckdb') para persistir

for table, file in files.items():
    con.execute(f"""
        CREATE TABLE {table} AS 
        SELECT * FROM read_csv_auto('data/{file}')
    """)

# Verificar qué tablas quedaron cargadas
con.execute("SHOW TABLES").fetchdf()

                  name
0       credit_history
1            customers
2    financial_profile
3    loan_applications
4       loan_decisions
5    new_loan_outcomes
6            new_loans
7  new_payment_history
8      payment_history
9       previous_loans

In [8]:
con.execute(
    f"""
    SELECT * FROM customers LIMIT 5;
    """
).fetchdf()

   customer_id birth_date  gender   education marital_status  dependents
0            1 1975-12-31  Female  University        Married           0
1            2 1973-12-31  Female   Secondary         Single           2
2            3 1983-12-31  Female   Secondary       Divorced           0
3            4 1987-12-31  Female   Secondary        Married           2
4            5 1975-12-31  Female   Secondary         Single           0